version: "3.6"

services:
  rabbitmq:
    image: "rabbitmq:3.12-management"
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      # The location of the RabbitMQ server. "amqp" is the protocol;
      # "rabbitmq" is the hostname.  Note that there is not a guarantee
      # that the server will start first!
      AMQP_URL: "amqp://rabbitmq?connection_attempts=5&retry_delay=5"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    networks:
      - rabbit

networks:
  rabbit:
    driver: bridge
